{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gfd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GFD_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GFD/GFD_{{ version }}.tar.gz
  sha256: f4be06c33c16a510afdd88ca68fcd92fd43645a75c16f109299c1f33267780b4

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass >=7.3_43
    - r-matrix >=1.2_2
    - r-magic >=1.5_6
    - r-plotrix >=3.5_12
    - r-plyr >=1.8.3
    - r-shiny >=1.4
    - r-shinywidgets
    - r-shinyjs
    - r-shinythemes
    - r-tippy
  run:
    - r-base
    - r-mass >=7.3_43
    - r-matrix >=1.2_2
    - r-magic >=1.5_6
    - r-plotrix >=3.5_12
    - r-plyr >=1.8.3
    - r-shiny >=1.4
    - r-shinywidgets
    - r-shinyjs
    - r-shinythemes
    - r-tippy

test:
  commands:
    - $R -e "library('GFD')"           # [not win]
    - "\"%R%\" -e \"library('GFD')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GFD
  license: GPL-2.0-or-later
  summary: Implemented are the Wald-type statistic, a permuted version thereof as well as the ANOVA-type statistic for general factorial designs, even with non-normal error terms and/or heteroscedastic variances, for crossed designs with an arbitrary number of factors and nested designs with up to three factors. Friedrich
    et al. (2017) <doi:10.18637/jss.v079.c01>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
